#!/usr/bin/env python3
"""Extract PPTX service-icon colors and emit a resIcon -> color dict.

Run this when a new AWS Architecture Icons deck ships; paste the output
into SERVICE_ICON_COLORS in validate_aws_fidelity.py so the per-service
colour check stays current.

Usage:
    python3 extract_service_colors.py /path/to/AWS-Architecture-Icons-Deck.pptx

Pipeline:
    1. Invoke inspect_aws_deck.py colors on the PPTX.
    2. Parse "<Label> ... ['#HEX']" lines.
    3. Map each label to a resIcon name via aws-icon-catalog.md plus a small
       override table (for labels like "Amazon Quick Suite" where a shorter
       name like "q" would otherwise win a substring match).
    4. Emit a Python dict literal; services present on multiple slides with
       different colors (e.g. plain "SageMaker" vs "SageMaker AI") are
       emitted as a set literal with an "ambiguous" comment.
"""
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
INSPECTOR = HERE / "inspect_aws_deck.py"
CATALOG = HERE.parent / "references" / "aws-icon-catalog.md"

# Labels whose shortest catalog substring match would be wrong.
# Example: "Amazon Q" is a substring of "Amazon Quick Suite" but each
# is a distinct service with its own resIcon + color.
OVERRIDES = {
    "amazon quick suite": "quick_suite",
    "amazon q": "q",
    "amazon quicksight": "quicksight",
    "aws identity and access management (iam)": "identity_and_access_management",
    "amazon forecast": "forecast",
    "amazon memorydb": "memorydb",
}


def run_inspector(pptx):
    result = subprocess.run(
        [sys.executable, str(INSPECTOR), str(pptx), "colors"],
        capture_output=True, text=True, check=True,
    )
    pat = re.compile(
        r"^\s+(.+?service icon\.?)\s+slide\d+\s+\S+\s+\['(#[0-9A-F]{6})'\]\s*$"
    )
    pairs = []
    for line in result.stdout.splitlines():
        m = pat.match(line)
        if m:
            label = m.group(1).strip().rstrip(".")
            pairs.append((label, m.group(2)))
    return pairs


def load_catalog_map():
    """Parse the icon catalog markdown to get a label -> resIcon map."""
    text = CATALOG.read_text()
    mapping = {}
    # Markdown table rows: | Amazon X ... | resicon_name ¹ |
    row_re = re.compile(
        r"^\|\s*(.+?)\s*\|\s*`([a-z0-9_]+)`(?:\s*[\u00b9\u00b2\u00b3]?)?\s*\|?\s*$"
    )
    for line in text.splitlines():
        m = row_re.match(line)
        if not m:
            continue
        label, icon = m.group(1).strip().lower(), m.group(2).strip()
        if label.startswith(("service", "---")):
            continue
        mapping[label] = icon
    return mapping


def label_to_icon(label, catalog):
    normalized = re.sub(r"\s+service icon\.?$", "", label.lower())
    if normalized in OVERRIDES:
        return OVERRIDES[normalized]
    if normalized in catalog:
        return catalog[normalized]
    for prefix in ("amazon ", "aws "):
        if normalized.startswith(prefix) and normalized[len(prefix):] in catalog:
            return catalog[normalized[len(prefix):]]
    # Longest-substring match, min length 6 (prevents "q" matching "quick")
    best = None
    for key, icon in catalog.items():
        if key in normalized and len(key) >= 6:
            if best is None or len(key) > len(best[0]):
                best = (key, icon)
    return best[1] if best else None


def emit(pairs, catalog):
    resolved = {}
    unresolved = []
    for label, color in pairs:
        icon = label_to_icon(label, catalog)
        if icon:
            resolved.setdefault(icon, []).append((label, color))
        else:
            unresolved.append((label, color))
    print("# resIcon -> official category color (from PPTX)")
    print("# Auto-generated by scripts/extract_service_colors.py")
    print("SERVICE_ICON_COLORS = {")
    for icon in sorted(resolved):
        colors = {c for _, c in resolved[icon]}
        if len(colors) == 1:
            print(f'    "{icon}": "{colors.pop()}",')
        else:
            cs = ", ".join(f'"{c}"' for c in sorted(colors))
            labs = ", ".join(sorted({lab for lab, _ in resolved[icon]}))
            print(f'    "{icon}": {{{cs}}},  # ambiguous: {labs}')
    print("}")
    if unresolved:
        print(f"\n# {len(unresolved)} services did not map to a catalog resIcon:")
        for lab, col in sorted(unresolved):
            print(f"#   {lab!r}  {col}")


def main():
    if len(sys.argv) < 2:
        print("Usage: extract_service_colors.py <deck.pptx>", file=sys.stderr)
        sys.exit(2)
    pptx = Path(sys.argv[1])
    if not pptx.exists():
        print(f"Deck not found: {pptx}", file=sys.stderr)
        sys.exit(2)
    emit(run_inspector(pptx), load_catalog_map())


if __name__ == "__main__":
    main()
